let products = [
  {
    id: "LD01",
    color: "cornflowerblue",
    name: "Scandi Lounge Chair",
    price: 100,
    about:
      "Minimalist lounge chair with a soft blue fabric and angled wooden legs.",
    img: "./assets/1.png",
    materials: ["Synthetic skin", "Metal"],
  },
  {
    id: "LD02",
    color: "tomato",
    name: "Urban Recliner",
    price: 200,
    about:
      "Comfortable recliner designed for small spaces, with a retro touch.",
    img: "./assets/2.png",
    materials: ["Wooden", "Polyurethane"],
  },
  {
    id: "LD03",
    color: "lightseagreen",
    name: "Vintage Velvet Armchair",
    price: 300,
    about: "Luxurious velvet armchair with elegant curves and sturdy legs.",
    img: "./assets/3.png",
    materials: ["Viscoelastic", "Metal"],
  },
  {
    id: "LD04",
    color: "sandybrown",
    name: "Nordic Fabric Chair",
    price: 400,
    about: "Scandinavian-style chair with soft upholstery and button accents.",
    img: "./assets/4.png",
    materials: ["Natural skin", "Metal"],
  },
  {
    id: "LD05",
    color: "lightgreen",
    name: "Copenhagen Reading Chair",
    price: 500,
    about: "Designed for long reading sessions with ergonomic back support.",
    img: "./assets/5.png",
    materials: ["Natural skin", "Foam"],
  },
  {
    id: "LD06",
    color: "mediumorchid",
    name: "Pastel Lounge Seat",
    price: 600,
    about:
      "Pastel-colored seat with mid-century design, perfect for modern homes.",
    img: "./assets/6.png",
    materials: ["Wooden", "Metal"],
  },
  {
    id: "LD07",
    color: "lightcoral",
    name: "Patchwork Kody Chair",
    price: 700,
    about:
      "A vibrant patchwork fabric on a classic wooden base for eclectic spaces.",
    img: "./assets/7.png",
    materials: ["Wooden", "Fabric"],
  },
  {
    id: "LD08",
    color: "pink",
    name: "Soft Hue Armchair",
    price: 800,
    about: "A cozy pink-toned chair with soft padding and rounded edges.",
    img: "./assets/8.png",
    materials: ["Foam", "Synthetic fiber"],
  },
  {
    id: "LD09",
    color: "tomato",
    name: "Retro Chic Armchair",
    price: 900,
    about: "Bold retro design with a mix of comfort and standout color.",
    img: "./assets/1.png",
    materials: ["Synthetic skin", "Metal"],
  },
  {
    id: "LD10",
    color: "sandybrown",
    name: "Elegant Fiber Armchair",
    price: 1000,
    about: "Elegant armchair crafted with natural fibers and metallic accents.",
    img: "./assets/1.png",
    materials: ["Natural fiber", "Metal"],
  },
  {
    id: "LD11",
    color: "gold",
    name: "Elegant Asror mebel Armchair",
    price: 1100,
    about: "Elegant armchair crafted with natural fibers and metallic accents.",
    img: "./assets/1.png",
    materials: ["Natural fiber", "Metal","Asror"],
  },
];
