const productList = [
    {
      id: "LD01",
      name: "Patio armchair, blue",
      color: "tomato",
      price: 100,
      about: "Armchair in scandinavian design upholstered with fabric Miss pattern. Backrest with decorative buttons. Legs in natural wood.",
      img: "./product-img/1.png",
      materials: "Metal",
    },
    {
      id: "LD02",
      name: "Patio armchair, blue",
      color: "cornflowerblue",
      price: 200,
      about: "Armchair in scandinavian design upholstered with fabric Miss pattern. Backrest with decorative buttons. Legs in natural wood.",
      img: "./product-img/2.png",
      materials: "Polyurethane",
    },
    {
      id: "LD03",
      name: "Arck armchair, pink",
      color: "lightseagreen",
      price: 300,
      about: "Armchair in scandinavian design upholstered with fabric Miss pattern. Backrest with decorative buttons. Legs in natural wood.",
      img: "./product-img/3.png", 
      materials: "Viscoelastic",

    },
    {
      id: "LD04",
      name: "Patio armchair, blue",
      color: "aqua",
      price: 400,
      about: "Armchair in scandinavian design upholstered with fabric Miss pattern. Backrest with decorative buttons. Legs in natural wood.",
      img: "./product-img/4.png",
      materials: "Natural skin",
    },
    {
      id: "LD05",
      name: "Patio armchair, blue",
      color: "red",
      price: 500,
      about: "Armchair in scandinavian design upholstered with fabric Miss pattern. Backrest with decorative buttons. Legs in natural wood.",
      img: "./product-img/5.png",
      materials: "Foam",
    },
    {
      id: "LD06",
      name: "Patio armchair, blue",
      color: "blue",
      price: 600,
      about: "Armchair in scandinavian design upholstered with fabric Miss pattern. Backrest with decorative buttons. Legs in natural wood.",
      img: "./product-img/6.png",
      materials: "Wooden",
    },
    {
      id: "LD07",
      name: "KodyArmchair patchwork",
      color: "green",
      price: 700,
      about: "Armchair in scandinavian design upholstered with fabric Miss pattern. Backrest with decorative buttons. Legs in natural wood.",
      img: "./product-img/7.png",
      materials: "Fabriс",
    },
    {
      id: "LD08",
      name: "Patio armchair, blue",
      color: "yellow",
      price: 800,
      about: "Armchair in scandinavian design upholstered with fabric Miss pattern. Backrest with decorative buttons. Legs in natural wood.",
      img: "./product-img/8.png",
      materials:  "Synthetic fiber",
    },
    {
      id: "LD09",
      name: "KodyArmchair patchwork",
      color: "grey",
      price: 900,
      about: "Armchair in scandinavian design upholstered with fabric Miss pattern. Backrest with decorative buttons. Legs in natural wood.",
      img: "./product-img/1.png",
      materials: "Synthetic skin",
    },
    {
      id: "LD10",
      name: "Patio armchair, blue",
      color: "pink",
      price: 1000,
      about: "Armchair in scandinavian design upholstered with fabric Miss pattern. Backrest with decorative buttons. Legs in natural wood.",
      img: "./product-img/1.png",
      materials:  "Metal",
    },
  ];
  